# Generated by Django 4.0.1 on 2022-01-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AVP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='Pin_Code',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='contact',
            field=models.IntegerField(default=0),
        ),
    ]
