# Generated by Django 4.0.1 on 2022-01-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AVP', '0002_alter_newuser_pin_code_alter_newuser_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
